# willshersystems.sshd
sshd_enable: True
sshd_skip_defaults: False
sshd_manage_service: True
sshd_allow_reload: True
sshd:
  AllowUsers:
    - josh
    - mokuno
    - logicmonitor
    - properlysortednyc
    - mjbeaumont
    - drankin
    - ansible-deploy
    - ilessing

  PubkeyAuthentication: True
  LogLevel: 'debug'
  UseDNS: 'no'
